AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SpringBoot API with the aws-lambda-web-adapter library

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Parameters:
  DatabaseUrl:
    Type: String
  AWSS3Bucket:
    Type: String
  AWSS3BucketBaseUrl:
    Type: String
  S3AccessPolicyArn:
    Type: String
  AWSBedrockModelId:
    Type: String

Resources:
  MmmFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 1512
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonBedrockFullAccess
        - !Ref S3AccessPolicyArn
      Timeout: 60
      Environment:
        Variables:
          RUST_LOG: info
          AWS_LWA_ASYNC_INIT: true
          SPRING_DATASOURCE_URL: !Ref DatabaseUrl
          AWS_S3_BUCKET: !Ref AWSS3Bucket
          AWS_S3_BUCKET_BASE_URL: !Ref AWSS3BucketBaseUrl
          AWS_BEDROCK_MODEL_ID: !Ref AWSBedrockModelId
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            TimeoutInMillis: 29000
            PayloadFormatVersion: '1.0'
    Metadata:
      DockerContext: .
      Dockerfile: Dockerfile

Outputs:
  SpringBootMmmApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com'
    Export:
      Name: SpringBootMmmApi
