AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SpringBoot API with the aws-lambda-web-adapter library

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Parameters:
  DatabaseUrl:
    Type: String
  AWSS3Bucket:
    Type: String
  AWSS3BucketBaseUrl:
    Type: String
  S3AccessPolicyArn:
    Type: String
  AWSBedrockModelId:
    Type: String

Resources:
  MmmFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 1512
      Handler: run.sh
      CodeUri: .
      Runtime: java21
      AutoPublishAlias: live
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonBedrockFullAccess
        - !Ref S3AccessPolicyArn
      Timeout: 60
      Environment:
        Variables:
          RUST_LOG: info
          AWS_LAMBDA_EXEC_WRAPPER: /opt/bootstrap
          SPRING_DATASOURCE_URL: !Ref DatabaseUrl
          AWS_S3_BUCKET: !Ref AWSS3Bucket
          AWS_S3_BUCKET_BASE_URL: !Ref AWSS3BucketBaseUrl
          AWS_BEDROCK_MODEL_ID: !Ref AWSBedrockModelId
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:753240598075:layer:LambdaAdapterLayerX86:24
      FunctionUrlConfig:
        AuthType: NONE

Outputs:
  MmmFunctionFunctionUrlEndpoint:
    Description: "The function URL endpoint for MmmFunction."
    Value:
      Fn::GetAtt: MmmFunctionUrl.FunctionUrl
